version: "3.3"
name: crud-web
services:
  crud-web:
    container_name: crud-react-web
    image: crud-react-web_image
    build: .
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    command: pnpm run preview

